<?php

	return [
		'empty' => 'No resellers found',

		'ref' => 'Reference',
		'ref.used' => 'This reference is already taken.',
		'type' => 'Type',
		'type.company' => 'Company',
		'type.individual' => 'Individual',
		'name' => 'Name',
		'email' => 'Email',
		'email.used' => 'This email is already taken.',
		'locale' => 'Language',
		'password' => 'Password',
		'password.helper' => 'Leave empty to keep current password.',
		'enabled' => 'Enabled',
		'commission' => 'Commission',
		'commission.default' => 'Default commission',
		'commission.fixed' => 'Fixed commission',
		'commission.variable' => 'Variable commission',

		'tab.general' => 'General',
		'tab.commissions' => 'Commissions',
		'tab.sites' => 'Sites',

		'create.title' => 'Create reseller',
		'edit.title' => 'Edit reseller',

		'sites.none' => 'No sites found',
		'sites.title' => 'Title',
		'sites.country' => 'Country',
		'sites.plan' => 'Plan',
		'sites.created' => 'Created',

		'payments.empty' => 'No payments found',
		'payments.reseller' => 'Reseller',
		'payments.reseller.name' => 'Name',
		'payments.reseller.email' => 'Email',
		'payments.reseller.fixed' => 'Fixed commission',
		'payments.reseller.variable' => 'Variable commission',
		'payments.reseller.total' => 'Total commission',
		'payments.amount' => 'Amount',
		'payments.created' => 'Created',
		'payments.site' => 'Site',
		'payments.paid' => 'Paid',
		'payments.paid.date' => 'Payment date',
		'payments.paid.from' => 'Paid from',
		'payments.paid.until' => 'Paid until',
		'payments.plan' => 'Plan',
		'payments.pay' => 'Mark as paid',
	];
