<?php

	return [
		'h1' => 'Properties',
		'empty' => 'No properties found',

		'button.new' => 'New property',

		'column.title' => 'Property',
		'column.location' => 'Location',
		'column.created' => 'Created',

		'ref' => 'Reference',
		'type' => 'Type',
		'mode' => 'Mode',
		'price' => 'Price',
		'price.min' => 'Price min',
		'price.max' => 'Price max',
		'currency' => 'Currency',
		'size' => 'Size',
		'size.min' => 'Size min',
		'size.max' => 'Size max',
		'size_unit' => 'Unit of area',
		'rooms' => 'Number of rooms',
		'baths' => 'Number of bathrooms',
		'enabled' => 'Enabled',
		'enabled.not' => 'Disabled',
		'home.slider' => 'In home',
		'highlighted' => 'Highlighted',
		'highlighted.not' => 'Not highlighted',
		'new.item' => 'New property',
		'opportunity' => 'Opportunity',
		'newly_build' => 'New construction',
		'second_hand' => 'Second hand',
		'bank_owned' => 'Bank ownership',
		'private_owned' => 'Private ownership',
		'services' => 'Services',
		'label' => 'Label',
		'show_address' => 'Show address',
		'zipcode' => 'Zipcode',
		'construction_year' => 'Construction year',
		'discount' => 'Discount',
		'price_before' => 'Old price',
		'discount_show' => 'Show discount',

		'energy.certificate' => 'Energy certificate',
		'energy.certificate.pending' => 'In process',
		'energy.certificate.pending.full' => 'Energy certificate in process',

		'create.title' => 'New property',
		'edit.title' => 'Edit property',

		'tab.general' => 'Property',
		'tab.location' => 'Location',
		'tab.text' => 'Text',
		'tab.images' => 'Images',
		'tab.employees' => 'Managers',
		'tab.lead' => 'Leads',
		'tab.transaction' => 'Transactions',
		'tab.reports' => 'Reports',
		'tab.logs' => 'Logs',
		'tab.seller' => 'Seller',
		'tab.pdf' => 'PDF',

		'country' => 'Country',
		'state' => 'State',
		'city' => 'City',
		'district' => 'District',
		'address' => 'Address',
		'address.type' => 'Type',
		'address.street' => 'Street',
		'address.number' => 'Number',
		'address.block' => 'Block',
		'address.stair' => 'Stair',
		'address.floor' => 'Floor',
		'address.door' => 'Door',
		'lat' => 'Latitude',
		'lng' => 'Longitude',
		'geolocate' => 'Geolocate',
		'geolocate.missing' => 'Address could not be geolocated',

		'title' => 'Title',
		'subtitle' => 'Subtitle',
		'description' => 'Description',
		'characteristics' => 'Characteristics',
		'image' => 'Image',

		'images.gallery' => 'Image gallery',
		'images.upload' => 'Image upload',
		'images.empty' => 'This property has no images',
		'images.helper' => "<p>We support JPG, PNG and GIF formats.</p><p>Images bigger than :IMAGE_MAXSIZE kilobytes will not be uploaded.</p>",
		'images.delete' => 'Are you sure you want to permanently delete this image?',
		'images.dropzone.helper' => 'Drop files or click to upload',
		'images.dropzone.error.size' => 'Image is bigger than :IMAGE_MAXSIZE kilobytes',
		'images.dropzone.nicename' => 'The image',

		'employees.empty' => 'No managers found',
		'employees.employee' => 'Name',
		'employees.email' => 'Email',
		'employees.dissociate' => 'Remove',
		'employees.dissociate.confirm' => 'Are you sure you want to remove this manager?',
		'employees.dissociated' => 'The manager was successfully removed',
		'employees.associate' => 'Add manager',
		'employees.associated' => 'Manager was successfully added',

		'created' => 'The property was successfully created',
		'saved' => 'The property was successfully updated',

		'delete' => 'Are you sure you want to permanently delete this property?',
		'deleted' => 'The property was successfully deleted',

		'edit.view' => 'Property view',

		'show.property.catch.edit' => 'Edit property',
		'show.property.catch.close' => 'Close transaction',
		'show.property.catch.none' => 'There is no catch / sale / rent data for this property',
		'show.property.catch.date' => 'Catch date',
		'show.property.catch.employee' => 'Catcher',
		'show.property.catch.success' => 'Data was succesfully saved',
		'show.property.catch.transaction.date' => 'Close date',
		'show.property.catch.close.responsible' => 'Responsible',
		'show.property.catch.status' => 'Status',
		'show.property.catch.status.cancel' => 'Cancelled',
		'show.property.catch.status.sold' => 'Sold',
		'show.property.catch.status.rent' => 'Rented',
		'show.property.catch.status.transfer' => 'Transfered',
		'show.property.catch.status.other' => 'Other',

		'show.property.catch.actions' => 'Options',
		'show.property.catch.actions.create' => 'Add transaction',
		'show.property.catch.actions.edit' => 'Modify transaction',
		'show.property.catch.actions.close' => 'Close transaction',

		'show.property.seller.title' => 'Seller information',
		'show.property.seller.name.first' => 'Seller name',
		'show.property.seller.name.last' => 'Seller surname',
		'show.property.seller.email' => 'Seller email',
		'show.property.seller.id' => 'Seller ID card',
		'show.property.seller.phone' => 'Seller phone',
		'show.property.seller.cell' => 'Seller movile',
		'show.property.price.min' => 'Minimum price',
		'show.property.price.min.help' => 'This is the minimum price for which the owner would be willing to close the transaction (sell, rent, etc.)',
		'show.property.commission' => 'Commission',
		'show.property.commission.fixed' => 'Fixed commission',
		'show.property.commission.variable' => 'Variable commission',
		'show.property.commission.total' => 'Total commission',

		'show.property.comment.title' => 'Comment',
		'show.property.comment.button' => 'Save comment',

		'show.transactions.none' => 'There are no transactions',
		'show.transactions.date' => 'Date',
		'show.transactions.seller' => 'Seller',
		'show.transactions.buyer' => 'Customer',
		'show.transactions.price' => 'Price',
		'show.transactions.reason' => 'Comments',
		'show.transactions.commission' => 'Commission earned',

		'logs.loading' => 'Loading',
		'logs.empty' => 'No logs found.',
		'logs.empty.details' => 'There are no details for this log',
		'logs.date' => 'Date',
		'logs.responsible' => 'Responsible',
		'logs.responsible.unknown' => '---',
		'logs.action' => 'Action',
		'logs.view' => 'View log',

		'logs.type.created' => 'Property created',
		'logs.type.updated' => 'Property updated',
		'logs.type.deleted' => 'Property deleted',

		'logs.value.old' => 'Old value',
		'logs.value.new' => 'New value',

		'show.kpis.none' => 'There is no data for this property',
		'show.kpis.leads' => 'Leads to close',
		'show.kpis.discount' => 'Discount over initial price',
		'show.kpis.days' => 'Days to close',
		'show.kpis.closed.by' => 'Closed by',

		'show.leads.empty' => 'No leads found',
		'show.leads.add' => 'Add lead',

		'marketplaces.intro' => 'Please check those marketplaces where you wish to publish this property.',
		'marketplaces.toall' => 'Include this property in all exports',
		'marketplaces.error' => 'This property cannot be published in this marketplace:',

		'tab.appraisal' => 'Appraisals',
		'tab.documents' => 'Documents',
		'documents.none' => 'No documents found',
		'documents.new' => 'New document',
		'documents.date' => 'Date',
		'documents.title' => 'Title',
		'documents.description' => 'Description',
		'documents.appraiser' => 'Appraiser',
		'documents.appraisal.value' => 'Appraisal value',
		'documents.file' => 'Document',
		'documents.delete.warning' => 'Are you sure you want to delete this document for good?',
		'documents.delete.success' => 'The document has been successfully deleted',

		'tab.details' => 'Details',
		'professional_enabled' => 'Professional enabled',
		'commercial_enabled' => 'Commercial enabled',
		'property_disposal' => 'Property disposal',
		'property_disposal.front' => 'Front',
		'property_disposal.back' => 'Back',
		'property_disposal.internal' => 'Internal',
		'property_condition' => 'Property condition',
		'building_condition' => 'Building condition',
		'condition.excelent' => 'Excelent',
		'condition.very_good' => 'Very good',
		'condition.good' => 'Good',
		'condition.modderate' => 'Modderate',
		'condition.poor' => 'Poor',
		'bedrooms' => 'Number of bedroms',
		'toilettes' => 'Number of toilettes',
		'covered_area' => 'Covered area',
		'semi_covered_area' => 'Semi covered area (Semi covered patio and terraces)',
		'uncovered_area' => 'Uncovered area (Uncovered patio and terraces)',
		'lot_area' => 'Lot area',
		'buildable_area' => 'Buildable area',
		'basement_area' => 'Basement area',
		'mezzanine_area' => 'Mezzanine area',
		'showcase_front' => 'Showcase front',
		'expenses' => 'Expenses (monthly)',
		'balcony_area' => 'Balcony area',
		'size_real' => 'Useful area',

		'imports.h1' => 'Import properties',
		'imports.intro' => '<p>If you already have a catalog of properties, you can load it quickly using a CSV file.</p>',
		'imports.create' => 'New import',
		'imports.version' => 'Version',
		'imports.version.sample' => 'Download sample file',
		'imports.date' => 'Date',
		'imports.file' => 'File',
		'imports.file.error.type' => 'Please select a CSV file',
		'imports.file.error.upload' => 'There was an error while uploading the file',
		'imports.status' => 'Status',
		'imports.created' => 'The import process is running. You can check its status in this page.',
		'imports.data_structure' => 'Data structure',
		'imports.file_upload' => 'Upload file',

		'imports.csv.header' => 'Do not modify or delete the top 3 rows.',

		'imports.csv.instructions.title' => 'Instructions',
		'imports.csv.instructions.intro' => '<ul>
												<li>Do not modify the CSV file headers.</li>
												<li>Do not leave empty lines. The import routine ends when an empty line is found.</li>
												<li>You must respect the field options, including uppercase/lowercase (see table below).</li>
											</ul>',
		'imports.csv.instructions.column' => 'Column',
		'imports.csv.instructions.type' => 'Type',
		'imports.csv.instructions.required' => 'Required',
		'imports.csv.instructions.options' => 'Options',
	];
