<?php

	return [
		'h1' => 'Propiedades',
		'empty' => 'No se encontraron propiedades',

		'button.new' => 'Nueva propiedad',

		'column.title' => 'Propiedad',
		'column.location' => 'Ubicación',
		'column.address' => 'Dirección',
		'column.created' => 'Creación',

		'ref' => 'Referencia',
		'type' => 'Tipo',
		'mode' => 'Modalidad',
		'price' => 'Precio',
		'price.min' => 'Precio min',
		'price.max' => 'Precio max',
		'currency' => 'Moneda',
		'size' => 'Superficie',
		'size.min' => 'Superficie min',
		'size.max' => 'Superficie max',
		'size_unit' => 'Unidad de medida',
		'rooms' => 'Número de habitaciones',
		'baths' => 'Número de baños',
		'enabled' => 'Habilitada',
		'enabled.not' => 'Inactiva en web',
		'home.slider' => 'En portada',
		'highlighted' => 'Destacada',
		'highlighted.not' => 'No destacada',
		'new.item' => 'Novedad',
		'opportunity' => 'Oportunidad',
		'newly_build' => 'Nueva construcción',
		'second_hand' => 'Segunda mano',
		'bank_owned' => 'De banco',
		'private_owned' => 'De particular',
		'services' => 'Servicios',
		'label' => 'Etiqueta',
		'show_address' => 'Mostrar dirección',
		'zipcode' => 'Código postal',
		'construction_year' => 'Año de construcción',
		'discount' => 'Descuento',
		'price_before' => 'Precio anterior',
		'discount_show' => 'Mostrar descuento',

		'energy.certificate' => 'Certificado energético',
		'energy.certificate.pending' => 'En trámite',
		'energy.certificate.pending.full' => 'Certificado energético en trámite',

		'create.title' => 'Nueva propiedad',
		'edit.title' => 'Editar propiedad',

		'tab.general' => 'Propiedad',
		'tab.location' => 'Unicación',
		'tab.text' => 'Textos',
		'tab.images' => 'Imágenes',
		'tab.employees' => 'Managers',
		'tab.lead' => 'Leads',
		'tab.transaction' => 'Transacciones',
		'tab.reports' => 'Reportes',
		'tab.logs' => 'Logs',
		'tab.seller' => 'Vendedor',
		'tab.pdf' => 'PDF',

		'country' => 'País',
		'state' => 'Provincia',
		'city' => 'Ciudad',
		'district' => 'Distrito',
		'address' => 'Dirección',
		'address.type' => 'Tipo',
		'address.street' => 'Calle',
		'address.number' => 'Número',
		'address.block' => 'Bloque',
		'address.stair' => 'Escalera',
		'address.floor' => 'Planta',
		'address.door' => 'Puerta',
		'lat' => 'Latitud',
		'lng' => 'Longitud',
		'geolocate' => 'Posicionar',
		'geolocate.missing' => 'La localización no puedo ser geolocalizada',

		'title' => 'Título',
		'subtitle' => 'Subtítulo',
		'description' => 'Descripción',
		'characteristics' => 'Características',
		'image' => 'Imagen',

		'images.gallery' => 'Galería de imágenes',
		'images.upload' => 'Subir imágenes',
		'images.empty' => 'Esta propiedad no tiene imágenes',
		'images.helper' => '<p>Aceptamos imagenes en formato JPG, PNG y GIF.</p><p>No se subirán imágenes con peso superior a :IMAGE_MAXSIZE kilobytes.</p>',
		'images.delete' => '¿Confirma que desea eliminar permanentemente esta images?',
		'images.dropzone.helper' => 'Arrastre las imágenes o haga click',
		'images.dropzone.error.size' => 'La imagen pesa mas de :IMAGE_MAXSIZE kilobytes',
		'images.dropzone.nicename' => 'La imagen',

		'employees.empty' => 'No se encontraron managers',
		'employees.employee' => 'Nombre',
		'employees.email' => 'Email',
		'employees.dissociate' => 'Eliminar',
		'employees.dissociate.confirm' => '¿Confirma qeu desea eliminar este manager?',
		'employees.dissociated' => 'El manager se ha eliminado correctamente',
		'employees.associate' => 'Añadir manager',
		'employees.associated' => 'El manager se ha añadido correctamente',

		'created' => 'La propiedad se ha creado correctamente',
		'saved' => 'La propiedad se ha guardado correctamente',

		'delete' => '¿Confirma qeu desea eliminar permanentemente esta La propiedad se ha creado correctamente?',
		'deleted' => 'La La propiedad se ha creado correctamente se ha eliminado correctamente',

		'edit.view' => 'Vista propiedad',

		'show.property.catch.edit' => 'Editar propiedad',
		'show.property.catch.close' => 'Cerrar transacción',
		'show.property.catch.none' => 'No hay datos de captación / venta / alquiler para esta propiedad',
		'show.property.catch.date' => 'Fecha de captación',
		'show.property.catch.employee' => 'Captador',
		'show.property.catch.success' => 'Los datos se han guardado correctamente',
		'show.property.catch.transaction.date' => 'Fecha de cierre',
		'show.property.catch.close.responsible' => 'Responsable',
		'show.property.catch.status' => 'Estado',
		'show.property.catch.status.cancel' => 'Cancelada',
		'show.property.catch.status.sold' => 'Vendida',
		'show.property.catch.status.rent' => 'Alquilada',
		'show.property.catch.status.transfer' => 'Traspasada',
		'show.property.catch.status.other' => 'Otro',

		'show.property.catch.actions' => 'Opciones',
		'show.property.catch.actions.create' => 'Añadir transacción',
		'show.property.catch.actions.edit' => 'Modificar transacción',
		'show.property.catch.actions.close' => 'Cerrar transacción',

		'show.property.seller.title' => 'Información del vendedor',
		'show.property.seller.name.first' => 'Nombre vendedor',
		'show.property.seller.name.last' => 'Apellido vendedor',
		'show.property.seller.email' => 'Email vendedor',
		'show.property.seller.id' => 'DNI vendedor',
		'show.property.seller.phone' => 'Teléfono vendedor',
		'show.property.seller.cell' => 'Móvil vendedor',
		'show.property.price.min' => 'Precio mínimo',
		'show.property.price.min.help' => 'Corresponde al precio mínimo por el que el propietario estaría dispuesto a cerrar la transacción (vender, alquilar, etc)',
		'show.property.commission' => 'Comisión',
		'show.property.commission.fixed' => 'Comisión fija',
		'show.property.commission.variable' => 'Comisión variable',
		'show.property.commission.total' => 'Comisión total',

		'show.property.comment.title' => 'Comentario',
		'show.property.comment.button' => 'Guardar comentario',

		'show.transactions.none' => 'No hay transacciones',
		'show.transactions.date' => 'Fecha',
		'show.transactions.seller' => 'Vendedor',
		'show.transactions.buyer' => 'Cliente',
		'show.transactions.price' => 'Precio',
		'show.transactions.reason' => 'Comentarios',
		'show.transactions.commission' => 'Comisión obtenida',

		'logs.loading' => 'Cargando',
		'logs.empty' => 'No se encontraron registros.',
		'logs.empty.details' => 'No hay detalles para este log',
		'logs.date' => 'Fecha',
		'logs.responsible' => 'Responsable',
		'logs.responsible.unknown' => '---',
		'logs.action' => 'Acción',
		'logs.view' => 'Ver log',

		'logs.type.created' => 'Propiedad creada',
		'logs.type.updated' => 'Propiedad actualizada',
		'logs.type.deleted' => 'Propiedad eliminada',

		'logs.value.old' => 'Valor antiguo',
		'logs.value.new' => 'Valor nuevo',

		'show.kpis.none' => 'No hay datos para esta propiedad',
		'show.kpis.leads' => 'Leads para cerrar',
		'show.kpis.discount' => 'Descuento sobre PVP inicial',
		'show.kpis.days' => 'Días para cerrar',
		'show.kpis.closed.by' => 'Cerrado por',

		'show.leads.empty' => 'No se encontraron leads',
		'show.leads.add' => 'Añadir lead',

		'marketplaces.intro' => 'Marque el checkbox de los marketplaces donde desea publicar esta propiedad.',
		'marketplaces.toall' => 'Incluir esta propriedad en todos los exports',
		'marketplaces.error' => 'Esta propiedad no puede publicarse en esta marketplace:',

		'tab.appraisal' => 'Tasaciones',
		'tab.documents' => 'Documentos',
		'documents.none' => 'No se encontraron documentos',
		'documents.new' => 'Nuevo documento',
		'documents.date' => 'Fecha',
		'documents.title' => 'Título',
		'documents.description' => 'Descripción',
		'documents.appraiser' => 'Tasador',
		'documents.appraisal.value' => 'Valor tasación',
		'documents.file' => 'Documento',
		'documents.delete.warning' => '¿Confirma que desea eliminar este documento permanentemente?',
		'documents.delete.success' => 'El documento se ha eliminado correctamente',

		'tab.details' => 'Detalles',
		'professional_enabled' => 'Apto Profesional',
		'commercial_enabled' => 'Apto Comercial',
		'property_disposal' => 'Disposicion del inmueble',
		'property_disposal.front' => 'Frontal',
		'property_disposal.back' => 'Trasero',
		'property_disposal.internal' => 'Interior',
		'property_condition' => 'Estado del inmueble',
		'building_condition' => 'Estado del edificio',
		'condition.excelent' => 'Excelente',
		'condition.very_good' => 'Muy bueno',
		'condition.good' => 'Bueno',
		'condition.modderate' => 'Moderado',
		'condition.poor' => 'Mal estado',
		'bedrooms' => 'Número de dormitorios',
		'toilettes' => 'Número de aseos',
		'covered_area' => 'Superficie Cubierta',
		'semi_covered_area' => 'Superficie Semicubierta (Patio semicubierto y Terrazas)',
		'uncovered_area' => 'Superficie Descubierta (Patio descubierto y Terrazas)',
		'lot_area' => 'Superficie de Terreno',
		'buildable_area' => 'Superficie Edificable',
		'basement_area' => 'Superficie Subsuelo',
		'mezzanine_area' => 'Superficie Entrepiso',
		'showcase_front' => 'Medida de Frente de vidriera',
		'expenses' => 'Gastos mensuales',
		'balcony_area' => 'Superficie de Balcón',
		'size_real' => 'Superficie útil',

		'imports.h1' => 'Importar propiedades',
		'imports.intro' => '<p>Si tienes un catálogo de propiedades, puedes realizar una importación masiva a través de un fichero CSV.</p>',
		'imports.create' => 'Nueva importación',
		'imports.version' => 'Versión',
		'imports.version.sample' => 'Descargar fichero de ejemplo',
		'imports.date' => 'Fecha',
		'imports.file' => 'Fichero',
		'imports.file.error.type' => 'Por favor seleccione un fichero csv',
		'imports.file.error.upload' => 'Ocurrió un error al cargar el fichero',
		'imports.status' => 'Estado',
		'imports.created' => 'El proceso de importación se ha iniciado correctamente. Puedes consultar el progreso en esta misma página.',
		'imports.data_structure' => 'Estructura de datos',
		'imports.file_upload' => 'Subir fichero',

		'imports.csv.header' => 'No modifique ni elimine las 3 filas superiores.',

		'imports.csv.instructions.title' => 'Instrucciones',
		'imports.csv.instructions.intro' => '<ul>
												<li>No modificar las cabeceras del fichero CSV.</li>
												<li>No dejar lineas en blanco. La rutina de importación termina cuando se encuentra una linea vacía.</li>
												<li>Se deben respetar los valores predeterminados, incluyendo mayúsculas/minúsculas (ver tabla inferior).</li>
											</ul>',
		'imports.csv.instructions.column' => 'Columna',
		'imports.csv.instructions.type' => 'Tipo',
		'imports.csv.instructions.required' => 'Requerida',
		'imports.csv.instructions.options' => 'Opciones',

		'attributes.habitaclia-city' => 'Población',
		'attributes.yaencontre-city' => 'Población (yaencotre)',

		'location.address' => 'Dirección',
		'location.city' => 'Ciudad',
		'location.zipcode' => 'Código Postal',
		'location.number' => 'Número calle',

		'email.sold.subject' => 'La propiedad ":title" ":reference" ha sido vendida',
		'email.sold.intro' => 'Hola, :name',
		'email.sold.body' => 'Contacte con nosotros para obtener más información de otras propiedades disponibles que puedan ser de su interés.'
		'email.price.fall.intro' => 'Hola, :name',
		'email.price.fall' => 'El precio de la propiedad :title ":reference" ha bajado. El precio actual es de :current.',
		'email.price.fallen.subject' => 'El precio de la propiedad ":reference" ha bajado',
	];
